# Generated by Django 4.1.10 on 2023-12-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_profile_date_of_birth"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
