# Generated by Django 4.1.10 on 2023-12-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
        ),
    ]
