# Generated by Django 4.1.10 on 2023-12-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_profile_date_of_birth_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="salt",
        ),
    ]
