# Generated by Django 4.1.10 on 2023-12-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_photo_remove_profile_photo_profile_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
    ]
